### ISSUE TITLE
Up to date?

### ISSUE THREAD

**Issue by dcts** [PromiseNetwork/firestore-deleter#22]
Just curious if this library is still up to date and in use? Wanted to implement myself and found on NPM. The `deleteAll` nuke mode makes me kind nervous to use this package on a productive app lol.

**Comment by shaneosullivan** [comment]
I haven't touched it in a while.  You definitely need to know what you're doing when using it, but it serves a singular purpose fairly well.  It may need updating to work with the latest Firebase SDK, but I haven't had a need to use it in a few years.  Pull requests welcome!

**Comment by dcts** [comment]
Thanks, will test it out. I also opened a feature request issue on the official repo, maybe you want to follow that thread:
https://github.com/firebase/firebase-admin-node/issues/1566
